In [4]:
# 必要なライブラリをimportします
import numpy as np
import time
from numpy.random import rand

# 行、列の大きさ
N = 150

# 行列を初期化し明日
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])
print('matA:', matA)
print('matB:', matB)
print('matC:', matC)

# Pythonのリストを使って計算します

# 開始時間を取得します
start = time.time()

# for命令を使って行列の掛け算を実行します
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]
print('matC:', matC)

print('Pythonの機能のみでの計算結果: %.2f[sec]' % float(time.time() - start))

# NumPyを使って計算します

# 開始時間を取得します
start = time.time()

# NumPyを使って行列の掛け算を実行します
matC = np.dot(matA, matB)
print('matC:', matC)

# 少数第2位の桁で打ち切っているのでNumPyは0.00[sec]と表示されます
print('NumPyを使った場合の計算結果: %.2f[sec]' % float(time.time() - start))

matA: [[0.87789324 0.92993142 0.53530246 ... 0.0873802  0.76808904 0.17311901]
 [0.94592906 0.45371838 0.16829713 ... 0.0643299  0.33675791 0.35321554]
 [0.10986591 0.68510218 0.97869865 ... 0.13599605 0.45234346 0.45072392]
 ...
 [0.03694548 0.9150827  0.63276331 ... 0.97153702 0.69675536 0.08639455]
 [0.1763937  0.25131255 0.51312122 ... 0.87740223 0.08938288 0.71006086]
 [0.10206531 0.75815447 0.95070767 ... 0.33325715 0.74745743 0.06297411]]
matB: [[0.39790198 0.38560791 0.97394316 ... 0.23184235 0.48049844 0.50397676]
 [0.25815139 0.34536002 0.83782803 ... 0.81584304 0.82588103 0.31246795]
 [0.84471699 0.90751552 0.61643445 ... 0.12010669 0.01360002 0.8259413 ]
 ...
 [0.62591597 0.85956279 0.08984604 ... 0.18385066 0.39184946 0.74373471]
 [0.04859269 0.55415315 0.68884058 ... 0.88975459 0.23188686 0.47841832]
 [0.05465633 0.17352173 0.12417486 ... 0.02112227 0.7870675  0.82828025]]
matC: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0

In [4]:
# 1次元配列(ndarray)の生成
import numpy as np

storages = [24, 3, 4, 23, 10, 12]                   # 普通の1次元配列
print(storages)
print(type(storages))                               # 型を出力

np_storages = np.array([24, 3, 4, 23, 10, 12])      # NumPy1次元配列
print(np_storages)
print(type(np_storages))                            # 型を出力

[24, 3, 4, 23, 10, 12]
<class 'list'>
[24  3  4 23 10 12]
<class 'numpy.ndarray'>


In [5]:
# 1次元配列の計算
# NumPyを使わないで実行
storages = [1, 2, 3, 4]
new_storages = []
for i in storages:
    i += i
    new_storages.append(i)
print(new_storages)

# NumPyを使って実行
import numpy as np
storages = np.array([1, 2, 3, 4])
new_storages = storages * 2    # NumPy配列はfor文を使わなくても簡単に計算ができる
print(new_storages)

[2, 4, 6, 8]
[2 4 6 8]


In [9]:
# インデックス参照とスライス
import numpy as np

arr = np.arange(10)         # 0から9までの10個の要素を持った配列を生成
print(arr)

print(arr[3:6])             # インデックス番号が3から5(6-1)までの配列を生成

arr[3:6] = 24               # インデックス番号が3から5(6-1)の値を変更
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


In [10]:
# ndarrayのコピー
import numpy as np

# ndarrayをそのまま別の変数に代入した場合の挙動
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
arr2 = arr1
arr2[0] = 100
print(arr1)         # arr2を変更すると、元のarr1にも変更が影響される

# copy()を使って別の変数に代入した場合の挙動
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
arr2 = arr1.copy()
arr2[0] = 100
print(arr1)         # arr2を変更しても、元のarr1には変更は影響されない

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


In [12]:
# viewとcopy
import numpy as np

# Pythonのリストでスライスを用いた場合の挙動
arr_list = [x for x in range(10)]
print('リスト型データです')
print('arr_list: ', arr_list)
print()
arr_list_copy = arr_list[:]
arr_list_copy[0] = 100
print('リストのスライスではコピーが作られるので、arr_listにはarr_list_copyの変更が反映されません')
print('arr_list: ', arr_list)
print()

# NumPyのndarrayでスライスを用いた場合での挙動
arr_numpy = np.arange(10)
print('NumPyのndarrayデータです')
print('arr_numpy: ', arr_numpy)
print()
arr_numpy_view = arr_numpy[:]
arr_numpy_view[0] = 100
print('numpyのスライスではview(データが格納されている場所の情報)が代入されるので、arr_numpy_viewの変更がarr_numpyに反映されます')
print('arr_numpy: ', arr_numpy)
print()

# NumPyのndarrayでcopy()を用いた場合での挙動
arr_numpy = np.arange(10)
print('NumPyのndarrayでcopy()を用いた場合での挙動です')
print('arr_numpy: ', arr_numpy)
print()
arr_numpy_copy = arr_numpy[:].copy()
arr_numpy_copy[0] = 100
print('copy()を用いた場合は、コピーが生成されているのでarr_numpy_copyはarr_numpyに影響を与えません')
print('arr_numpy: ', arr_numpy)

リスト型データです
arr_list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

リストのスライスではコピーが作られるので、arr_listにはarr_list_copyの変更が反映されません
arr_list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

NumPyのndarrayデータです
arr_numpy:  [0 1 2 3 4 5 6 7 8 9]

numpyのスライスではview(データが格納されている場所の情報)が代入されるので、arr_numpy_viewの変更がarr_numpyに反映されます
arr_numpy:  [100   1   2   3   4   5   6   7   8   9]

NumPyのndarrayでcopy()を用いた場合での挙動です
arr_numpy:  [0 1 2 3 4 5 6 7 8 9]

copy()を用いた場合は、コピーが生成されているのでarr_numpy_copyはarr_numpyに影響を与えません
arr_numpy:  [0 1 2 3 4 5 6 7 8 9]


In [16]:
# ブルーインデックス参照
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])
print(arr % 2 == 0)
print()
print(arr[arr % 2 == 0])

[ True False  True False  True False]

[2 4 6]


In [17]:
# ユニバーサル関数
# ndarray配列の各要素に対して演算した結果を返す関数のこと
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

arr_abs = np.abs(arr)
print(arr_abs)              # 絶対値

print(np.exp(arr_abs))      # eのべき乗
print(np.sqrt(arr_abs))     # 平方根

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [21]:
# 集合関数
# 数学の集合演算を行う関数(1次元配列のみが対象)
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

new_arr1 = np.unique(arr1)              # 重複を取り除く
print(new_arr1)

print(np.union1d(new_arr1, arr2))       # 和集合

print(np.intersect1d(new_arr1, arr2))   # 積集合

print(np.setdiff1d(new_arr1, arr2))     # 差集合

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


In [25]:
# 乱数
import numpy as np

from numpy.random import randint

arr1 = randint(0, 11, (5, 2))   # 0以上10未満の整数の行列(5, 2)
print(arr1)

arr2 = np.random.rand(3)        # 0以上1未満の一様乱数3つ
print(arr2)

[[10  4]
 [ 6  3]
 [ 0  4]
 [10  3]
 [ 3  5]]
[0.69135571 0.67066379 0.38902883]
