In [1]:
# 2次元配列
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

print(arr.shape)            # 配列のサイズを取得

print(arr.reshape(4, 2))    # 配列のサイズを変更

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# インデックス参照とスライス
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

print(arr[0][2])

print(arr[1:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


In [1]:
# axis
# 行をaxis=1で、列をaxis=0で引数に指定できる
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

print(arr.sum(axis=1))      # 行列の和を行単位で求める

[ 6 21 57]


In [3]:
# ファンシーインデックス参照
# インデックス参照にインデックスの配列を用いる方法
# スライスとは異なり、ファンシーインデックス参照は常に元データのコピーを返す
import numpy as np

arr = np.arange(25).reshape(5, 5)       # 5x5行列を作成(1x25行列を変形)
print(arr)

print(arr[[1, 3, 0]])       # 配列を用いた参照(1, 3, 0行目を順番に取得))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [4]:
# 転置行列
import numpy as np

arr = np.arange(10).reshape(2, 5)
print(arr)

print(arr.T)                # 配列を転置させる(2x5行列なら5x2行列にする)
print(np.transpose(arr))    # 同上

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [6]:
# ソート
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

print(arr.argsort())    # 元の配列のインデックス番号を並べ替えして返す

print(np.sort(arr))     # ソートした配列を返す

arr.sort(1)             # 配列を直接ソートする
print(arr)

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]


In [19]:
# 行列計算
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)

print(np.dot(arr, arr))         # 行列積

vec = arr.reshape(9)
print(vec)

print(np.linalg.norm(vec))      # ノルム

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[0 1 2 3 4 5 6 7 8]
14.2828568570857


In [2]:
# 統計関数
# ndarray配列全体、もしくは特定の軸を中心とした数学的な処理を行う関数、またはメソッドのこと
import numpy as np

arr = np.arange(15).reshape(3, 5)
print(arr)

print(arr.mean(axis=0))     # 平均値を列単位で求める

print(arr.sum(axis=1))      # 合計値を行単位で求める

print(arr.min())            # 最小値を求める

print(arr.argmax(axis=0))   # 最大値を列単位でインデックス番号で取得

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


In [22]:
# ブロードキャスト
# 2つのndarray同士の演算時にサイズの小さい配列の行と列を自動で大きい配列に合わせる
# 2つの配列の行または列が一致しないときは、業の少ないほうが多い方の数に合わせ、足りない分を既存の行からコピーする
import numpy as np

x = np.arange(15).reshape(3, 5)
print(x)

y = np.array([np.arange(5)])
print(y)

z = x - y
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1 2 3 4]]
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
