#  Chapter7　NumPy

- **7.1 NumPy の概観**
    - **7.1.1 NumPyとは**
    - **7.1.2 NumPyの高速な処理の体験**
<br><br>
- **7.2 NumPy 1次元配列**
    - **7.2.1 import**
    - **7.2.2 1次元配列**
    - **7.2.3 1次元配列の計算**
    - **7.2.4 インデックス参照とスライス**
    - **7.2.5 ndarrayの注意点**
    - **7.2.6 viewとcopy**
    - **7.2.7 ブールインデックス参照** 
    - **7.2.8 ユニバーサル関数**
    - **7.2.9 集合関数**  
    - **7.2.10 乱数**
<br><br>
- **7.3 NumPy 2次元配列**
    - **7.3.1 2次元配列**
    - **7.3.2 インデックス参照とスライス**
    - **7.3.3 axis**
    - **7.3.4 ファンシーインデックス参照**
    - **7.3.5 転置行列**
    - **7.3.6 ソート**
    - **7.3.7 行列計算**
    - **7.3.8 数学関数**
    - **7.3.9 ブロードキャスト**
<br><br>
- **添削問題**
- **総合添削問題**

## ●7.1 NumPy の概観

### ○7.1.1 NumPy とは

この項にサンプルはありません

### ○7.1.2 NumPyの高速な処理の体験

#### □問題


In [ ]:
# 必要なライブラリをimportします
import numpy as np
import time
from numpy.random import rand

# 行、列の大きさ
N = 150

# 行列を初期化します
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

# Pythonのリストを使って計算します

# 開始時間を取得します
start = time.time()

# for文を使って行列の掛け算を実行します
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("Pythonの機能のみでの計算結果：%.2f[sec]" % float(time.time() - start))

# NumPyを使って計算します

# 開始時間を取得します
start = time.time()

# NumPyを使って行列の掛け算を実行します
matC = np.dot(matA, matB)

# 少数第2位の桁で打ち切っているのでNumPyは0.00[sec]と表示されます
print("NumPyを使った場合の計算結果：%.2f[sec]" % float(time.time() - start))

**リスト7.2：問題**

#### □解答例（出力結果は誌面と異なります）

In [1]:
# 必要なライブラリをimportします
import numpy as np
import time
from numpy.random import rand

# 行、列の大きさ
N = 150

# 行列の初期化します
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

# Pythonのリストを使って計算します

# 開始時間を取得します
start = time.time()

# for文を使って行列の掛け算を実行します
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("Pythonの機能のみでの計算結果：%.2f[sec]" % float(time.time() - start))

# NumPyを使って計算します

# 開始時間を取得します
start = time.time()

# NumPyを使って行列の掛け算を実行します
matC = np.dot(matA, matB)

# 少数第2位の桁で打ち切っているのでNumPyは0.00[sec]と表示されます
print("NumPyを使った場合の計算結果：%.2f[sec]" % float(time.time() - start))

Pythonの機能のみでの計算結果：3.20[sec]
NumPyを使った場合の計算結果：0.32[sec]


**リスト7.2：解答例**

## ○7.2 NumPy 1次元配列

### □7.2.1 import

#### □問題

In [ ]:
# NumPyをimportしてください



**リスト7.3：問題**

#### □解答例

In [2]:
# NumPyをimportしてください
import numpy as np

**リスト7.4：解答例**

### ○7.2.2 1次元配列

#### □問題

In [ ]:
import numpy as np

storages = [24, 3, 4, 23, 10, 12]
print(storages)

# ndarray配列を生成し、変数np_storagesに代入してください


# 変数np_storagesの型を出力してください
print()

**リスト7.5：問題** 修正 余計な行削除

#### □解答例

In [3]:
import numpy as np

storages = [24, 3, 4, 23, 10, 12]
print(storages)

# ndarray配列を生成し、変数np_storagesに代入してください
np_storages = np.array(storages)

# 変数np_storagesの型を出力してください
print(type(np_storages))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


**リスト7.6：解答例**

### ○7.2.3 1次元配列の計算

In [5]:
# NumPyを使わないで実行します
storages = [1, 2, 3, 4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


**リスト7.7：1 次元配列の計算の例①**

In [6]:
# NumPyを使って実行します
import numpy as np
storages = np.array([1, 2, 3, 4])
storages += storages
print(storages)

[2 4 6 8]


**リスト 7.8：1 次元配列の計算の例②**

#### □問題


In [ ]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print()

# arr - arr
print()

# arr ** 3
print()

# 1 / arr
print()

**リスト7.9：問題**

#### □解答例

In [7]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print('arr + arr')
print(arr + arr)
print()

# arr - arr
print('arr - arr')
print(arr - arr)
print()

# arr ** 3
print('arr ** 3')
print(arr ** 3)
print()

# 1 / arr
print('1 / arr')
print(1 / arr)
print()

arr + arr
[ 4 10  6  8 16]

arr - arr
[0 0 0 0 0]

arr ** 3
[  8 125  27  64 512]

1 / arr
[0.5        0.2        0.33333333 0.25       0.125     ]



**リスト7.10：解答例**

### ○7.2.4 インデックス参照とスライス

In [8]:

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**リスト7.11：スライスの例①**　

In [12]:
arr = np.arange(10)
arr[0:3] = 1
print(arr)

[1 1 1 3 4 5 6 7 8 9]


**リスト7.12：スライスの例②**

#### □問題

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)

# 変数arrの要素のうち3, 4, 5だけを出力してください
print()

# 変数arrの要素のうち3, 4, 5を24に変更してください

print(arr)

**リスト7.13：問題**

#### □解答例

In [9]:
import numpy as np

arr = np.arange(10)
print(arr)

# 変数arrの要素のうち3, 4, 5だけを出力してください
print(arr[3:6])

# 変数arrの要素のうち3, 4, 5を24に変更してください
arr[3:6] = 24
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


**リスト7.14：解答例**

### ○7.2.5 ndarrayの注意点

#### □問題


In [ ]:
import numpy as np

# ndarrayをそのまま別の変数に代入した場合の挙動を見て行きましょう
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# 別の変数への変更が元の変数にも影響されています
print(arr1)

# ndarrayをcopy( )を使って別の変数に代入した場合の挙動を見て行きましょう
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# 別の変数への変更が元の変数には影響を与えていません
print(arr1)

**リスト7.15：問題**

#### □解答例

In [10]:
import numpy as np

# ndarrayをそのまま別の変数に代入した場合の挙動を見て行きましょう
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# 別の変数への変更が元の変数にも影響されています
print(arr1)

# ndarrayをcopy( )を使って別の変数に代入した場合の挙動を見て行きましょう
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# 別の変数への変更が元の変数には影響を与えていません
print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


**リスト7.16：解答例**

### ○7.2.6 viewとcopy

#### □問題


In [ ]:
import numpy as np

# Pythonのリストでスライスを用いた場合の挙動を確認しましょう
arr_List = [x for x in range(10)]
print("リスト型データです")
print("arr_List:",arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100


print("リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません")
print("arr_List:",arr_List)
print()

# NumPyのndarrayでスライスを用いた場合での挙動を確認しましょう
arr_NumPy = np.arange(10)
print("NumPyのndarrayデータです")
print("arr_NumPy:",arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

print("NumPyのスライスではview(データが格納されている場所の情報)が代入されるので、arr_NumPy_viewの変更がarr_NumPyに反映されます")
print("arr_NumPy:",arr_NumPy)
print()

# NumPyのndarrayでcopy()を用いた場合での挙動を確認しましょう
arr_NumPy = np.arange(10)
print('NumPyのndarrayでcopy()を用いた場合での挙動です')
print("arr_NumPy:",arr_NumPy)
print()
arr_NumPy_copy = arr_NumPy[:].copy()
arr_NumPy_copy[0] = 100

print("copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません")
print("arr_NumPy:",arr_NumPy)

**リスト7.17：問題**

#### □解答例

In [1]:
import numpy as np

# Pythonのリストでスライスを用いた場合の挙動を確認しましょう
arr_List = [x for x in range(10)]
print("リスト型データです")
print("arr_List:",arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100

print("リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません")
print("arr_List:",arr_List)
print()

# NumPyのndarrayでスライスを用いた場合での挙動を確認しましょう
arr_NumPy = np.arange(10)
print("NumPyのndarrayデータです")
print("arr_NumPy:",arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

print("NumPyのスライスではview(データが格納されている場所の情報)が代入されるので、arr_NumPy_viewの変更がarr_NumPyに反映されます")
print("arr_NumPy:",arr_NumPy)
print()

# NumPyのndarrayでcopy()を用いた場合での挙動を確認しましょう
arr_NumPy = np.arange(10)
print('NumPyのndarrayでcopy()を用いた場合での挙動です')
print("arr_NumPy:",arr_NumPy)
print()
arr_NumPy_copy = arr_NumPy[:].copy()
arr_NumPy_copy[0] = 100

print("copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません")
print("arr_NumPy:",arr_NumPy)

リスト型データです
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません
arr_List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

NumPyのndarrayデータです
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]

NumPyのスライスではview(データが格納されている場所の情報)が代入されるので、arr_NumPy_viewの変更がarr_NumPyに反映されます
arr_NumPy: [100   1   2   3   4   5   6   7   8   9]

NumPyのndarrayでcopy()を用いた場合での挙動です
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]

copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません
arr_NumPy: [0 1 2 3 4 5 6 7 8 9]


**リスト7.18：解答例**

### ○7.2.7 ブールインデックス参照

In [13]:
arr = np.array([2, 4, 6, 7]) 
print(arr[np.array([True, True, True, False])])  

[2 4 6]


**リスト7.19：ブールインデックス参照の例①**

In [16]:
arr = np.array([2, 4, 6, 7]) 
print(arr[arr % 3 == 1])

[4 7]


**リスト7.20：ブールインデックス参照の例②**

#### □問題


In [ ]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])

# 変数arrの各要素が2で割り切れるかどうかを示す真偽値の配列を出力してください
print()

# 変数arr各要素のうち2で割り切れる要素の配列を出力してください
print()

**リスト7.21：問題**

#### □解答例

In [17]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])

# 変数arrの各要素が2で割り切れるかどうかを示す真偽値の配列を出力してください
print(arr % 2 == 0)

# 変数arr各要素のうち2で割り切れる要素の配列を出力してください
print(arr[arr % 2 == 0])

[ True False  True False  True False]
[2 4 6]


**リスト7.22：解答例**

### ○7.2.8 ユニバーサル関数

#### □問題


In [ ]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 変数arrの各要素を絶対値にし、変数arr_absに代入してください
arr_abs = 
print(arr_abs)

# 変数arr_absの各要素のeのべき乗と平方根を出力してください
print()
print()

**リスト7.23：問題**

#### □解答例

In [18]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 変数arrの各要素を絶対値にし、変数arr_absに代入してください
arr_abs = np.abs(arr)
print(arr_abs)

# 変数arr_absの各要素のeのべき乗と平方根を出力してください
print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


**リスト7.24：解答例**

### ○7.2.9 集合関数

#### □問題


In [ ]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# np.unique()関数を用いて重複をなくした配列を変数new_arr1に代入してください
new_arr1 = 
print(new_arr1)

# 変数new_arr1と変数arr2の和集合を出力してください
print()

# 変数new_arr1と変数arr2の積集合を出力してください
print()

# 変数new_arr1から変数arr2を引いた差集合を出力してください
print()

**リスト7.25：問題**

#### □解答例

In [19]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# np.unique()関数を用いて重複をなくした配列を変数new_arr1に代入してください
new_arr1 = np.unique(arr1)
print(new_arr1)

# 変数new_arr1と変数arr2の和集合を出力してください
print(np.union1d(new_arr1, arr2))

# 変数new_arr1と変数arr2の積集合を出力してください
print(np.intersect1d(new_arr1, arr2))

# 変数new_arr1から変数arr2を引いた差集合を出力してください
print(np.setdiff1d(new_arr1, arr2))

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


**リスト7.26：解答**

### ○7.2.10 乱数

#### □問題


In [ ]:
import numpy as np

# randint()関数を np.randomと付けなくても良いように importしてください


# 変数 arr1に、各要素が 0 以上 10 以内の整数の行列 (5 × 2)を代入してください
arr1 = 
print(arr1)

# 変数 arr2に 0～1までの一様乱数を 3 つ代入してください
arr2 = 
print(arr2)

**リスト7.27：問題**

#### □解答例（出力結果は誌面と異なります）

In [20]:
import numpy as np

# randint()関数を np.randomと付けなくても良いように importしてください
from numpy.random import randint

# 変数 arr1に、各要素が 0 以上 10 以内の整数の行列 (5 × 2)を代入してください
arr1 = randint(0, 11, (5, 2))
print(arr1)

# 変数 arr2に 0～1までの一様乱数を 3 つ代入してください
arr2 = np.random.rand(3)
print(arr2)

[[6 7]
 [0 6]
 [9 5]
 [4 8]
 [7 7]]
[0.63789953 0.25708531 0.05888615]


**リスト7.28：解答例**

## ●7.3 NumPy 2次元配列

### ○7.3.1 2次元配列

#### □問題


In [ ]:
import numpy as np

# 変数arrに2次元配列を代入してください
arr = 
print(arr)

# 変数arrの行列の各次元ごとの要素数を出力してください
print()

# 変数arrを4行2列の行列に変換してください
print()

**リスト 7.29：問題**

#### □解答例

In [21]:
import numpy as np

# 変数arrに2次元配列を代入してください
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

# 変数arrの行列の各次元ごとの要素数を出力してください
print(arr.shape)

# 変数arrを4行2列の行列に変換してください
print(arr.reshape(4, 2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**リスト7.30：解答例**

### ○7.3.2 インデックス参照とスライス

In [22]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1])

[4 5 6]


**リスト7.31：インデックス参照の例①**

In [23]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,2])

6


**リスト7.32：インデックス参照の例②**

In [24]:
# リスト7.33
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,1:])

[5 6]


**リスト7.33：スライスの例**

#### □問題


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 変数arrの要素のうち3を出力してください
print()

# 変数arrから取り出し出力してください
print()

**リスト7.34：問題**

#### □解答例

In [25]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 変数arrの要素のうち3を出力してください
print(arr[0, 2])

# 変数arrから取り出し出力してください
# 以下では、「1行目以降」と「２列目まで」を取り出しています
print(arr[1:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


**リスト7.35：解答例**

### ○7.3.3 axis

In [26]:
arr = np.array([[1, 2 ,3], [4, 5, 6]])

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


**リスト7.36：axis の例**

#### □問題


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

# arrの行の合計値を求め、問題文の1次元配列を返してください
print()

**リスト7.37：問題**

#### □解答例

In [27]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

# arrの行の合計値を求め、問題文の1次元配列を返してください
print(arr.sum(axis=1))

[ 6 21 57]


**リスト7.38：解答例**

### ○7.3.4 ファンシーインデックス参照

In [28]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) 

# 3行目、2行目、0行目の順番に行の要素を抽出し、新しい要素を作成します
# インデックス番号は0から始まります
print(arr[[3, 2, 0]]) 

[[7 8]
 [5 6]
 [1 2]]


**リスト7.39：ファンシーインデックス参照の例**

#### □問題


In [ ]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

# 変数arrの行の順番を変更したものを出力してください
print()

**リスト7.40：問題**

#### □解答例

In [28]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

# 変数arrの行の順番を変更したものを出力してください
print(arr[[1, 3, 0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


**スト7.41：解答例**

### ○7.3.5 転置行列

#### □問題


In [ ]:
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 変数arrを転置させてください
print()

**リスト7.42：問題**

#### □解答例

In [29]:
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 変数arrを転置させてください
print(arr.T) # print(np.transpose(arr))

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


**リスト7.43：解答例**

### ○7.3.6 ソート

In [29]:
arr = np.array([15, 30, 5])
arr.argsort()

array([2, 0, 1], dtype=int64)

**リスト7.44：ソートの例**

#### □問題


In [ ]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# # argsort()メソッドを用いて出力してください
print()

# np.sort()関数を用いてソートし出力してください
print()

# sort()メソッドを用いて行でソートしてください

print(arr)

**リスト7.45：問題**

#### □解答例

In [30]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# argsort()メソッドを用いて出力してください
print(arr.argsort())

# np.sort()関数を用いてソートし出力してください
print(np.sort(arr))

# sort()メソッドを用いて行でソートしてください
arr.sort(1)
print(arr)

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]


**リスト7.46：解答例**　

### ○7.3.7 行列計算

#### □問題


In [ ]:
import numpy as np

# arrを定義します
arr = np.arange(9).reshape(3, 3)

# 変数arrとarrの行列積を出力してください
print()

# vecを定義します
vec = arr.reshape(9)

# 変数vecのノルムを出力してください
print()

**リスト7.47：問題**

#### □解答例

In [31]:
import numpy as np

# arrを定義します
arr = np.arange(9).reshape(3, 3)

# 変数arrとarrの行列積を出力してください
print(np.dot(arr, arr))

# vecを定義します
vec = arr.reshape(9)

# 変数vecのノルムを出力してください
print(np.linalg.norm(vec))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
14.2828568570857


**リスト7.48：解答例**

### ○7.3.8 統計関数 

#### □問題


In [ ]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

# 変数arrの列ごとの平均を出力してください
print()

# 変数arrの行の合計を出力してください
print()

# 変数arrの最小値を出力してください
print()

# 変数arrのそれぞれの列の最大値のインデックス番号を出力してください
print()

**リスト7.49：問題**

#### □解答例

In [31]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

# 変数arrの列ごとの平均を出力してください
print(arr.mean(axis=0))

# 変数arrの行の合計を出力してください
print(arr.sum(axis=1))

# 変数arrの最小値を出力してください
print(arr.min())

# 変数arrのそれぞれの列の最大値のインデックス番号を出力してください
print(arr.argmax(axis=0))

[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


**リスト 7.50：解答例**

### ○7.3.9 ブロードキャスト

In [34]:
x = np.arange(6).reshape(2, 3)
print(x + 1)

[[1 2 3]
 [4 5 6]]


**リスト7.51：ブロードキャストの例**

#### □問題

In [ ]:
import numpy as np



# 0から14の整数値をもつ3×5のndarray配列xを生成します
x = np.arange(15).reshape(3, 5)

# 0から4の整数値をもつ1×5のndarray配列yを生成します
y = np.array([np.arange(5)])

# xのn番目の列のすべての行からnだけ引いてください
z = 

# xを出力します
print(z)

**リスト7.52：問題**

#### □解答例

In [35]:
import numpy as np


# 0から14の整数値をもつ3×5のndarray配列xを生成します
x = np.arange(15).reshape(3, 5)

# 0から4の整数値をもつ1×5のndarray配列yを生成します
y = np.array([np.arange(5)])

# xのn番目の列のすべての行からnだけ引いてください
z = x - y

# xを出力します
print(z)

[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]


**リスト 7.53：解答例**

## ●7.3 添削問題

#### □問題


In [ ]:
import numpy as np


np.random.seed(100)

# 各要素が0~30の整数の行列（5×3）を変数arrに代入してください

print(arr)

# 変数arrを転置してください

print(arr)

# 変数arrの2, 3, 4列のみの行列(3×3)を変数arr1に代入してください

print(arr1)

# 変数arr1を行でソートしてください

print(arr1)

# 各列の平均を出力してください



**リスト7.54：問題**

#### □解答例

In [32]:
import numpy as np


np.random.seed(100)

# 各要素が0~30の整数の行列（5×3）を変数arrに代入してください
arr = np.random.randint(0, 31, (5, 3))
print(arr)

# 変数arrを転置してください
arr = arr.T
print(arr)

# 変数arrの2, 3, 4列のみの行列(3×3)を変数arr1に代入してください
arr1 = arr[:, 1:4]
print(arr1)

# 変数arr1を行でソートしてください
arr1.sort(0)
print(arr1)

# 各列の平均を出力してください
print(arr1.mean(axis = 0))

[[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]
[[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]
[[ 7 16 20]
 [23 10  2]
 [15 30 21]]
[[ 7 10  2]
 [15 16 20]
 [23 30 21]]
[15.         18.66666667 14.33333333]


**リスト7.55：解答例**

# ●総合添削問題

### □問題

In [ ]:
import numpy as np

# 乱数を初期化します
np.random.seed(0)

# 縦の大きさ、横の大きさを渡されたときに乱数で指定の大きさの画像を生成する関数です
def make_image(m, n):
    
    # n×m行列の各成分を0~5の値でランダムに満たしてください

    
    return image


# 渡された行列の一部を変更する関数です
def change_little(matrix):
    # 与えられた行列の形を取得し、shapeに代入してください

    
    # 行列の各成分について、変更するかしないかをランダムに決めた上で
    # 変更する場合は0~5のいずれかの整数にランダムに入れ替えてください
    
    
    
    
    return matrix

# ランダムに画像を作成します
image1 = make_image(3, 3)
print(image1)
print()

# ランダムに変更を適用します
image2 = change_little(np.copy(image1))
print(image2)
print()

# image1とimage2の差分を計算し、image3に代入してください

print(image3)
print()

# image3の各成分が絶対値である行列をもとめimage3に再代入してください


# image3を出力します
print(image3)

**リスト7.56：問題**

###  □解答例

In [33]:
import numpy as np

# 乱数を初期化します
np.random.seed(0)

# 縦の大きさ、横の大きさを渡されたときに乱数で指定の大きさの画像を生成する関数です
def make_image(m, n):
    
    # n×m行列の各成分を0~5の値でランダムに満たしてください
    image = np.random.randint(0, 6, (m, n))
        
    return image

# 渡された行列の一部を変更する関数です
def change_little(matrix):
    # 与えられた行列の形を取得し、shapeに代入してください
    shape = matrix.shape
    
    # 行列の各成分について、変更するかしないかをランダムに決めた上で
    # 変更する場合は0~5のいずれかの整数にランダムに入れ替えてください
    for i in range(shape[0]):
        for j in range(shape[1]):
            if np.random.randint(0, 2)==1:
                matrix[i][j] = np.random.randint(0, 6, 1)
    return matrix

# ランダムに画像を作成します
image1 = make_image(3, 3)
print(image1)
print()

# ランダムに変更を適用します
image2 = change_little(np.copy(image1))
print(image2)
print()

# image1とimage2の差分を計算し、image3に代入してください
image3 = image2 - image1
print(image3)
print()

# image3の各成分が絶対値である行列をもとめimage3に再代入してください
image3 = np.abs(image3)

# image3を出力します
print(image3)

[[4 5 0]
 [3 3 3]
 [1 3 5]]

[[4 5 0]
 [3 3 3]
 [0 5 5]]

[[ 0  0  0]
 [ 0  0  0]
 [-1  2  0]]

[[0 0 0]
 [0 0 0]
 [1 2 0]]


**リスト7.57：解答例**