In [1]:
# 配列を生成する方法
# (1) リテラル
arr = [1, 2, 3]
print(arr)
# (2) リスト内包表記
arr = [i for i in range(1, 4)]
print(arr)
# (3) range関数とlist関数
arr = list(range(1, 4))
print(arr)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [12]:
# range関数の使い方
print(list(range(10)))          # 0~9(10-1)の要素を持つ配列を生成
print(list(range(3, 10)))       # 3~9(10-1)の要素を持つ配列を生成
print(list(range(3, 10, 2)))    # 3~9(10-1)の要素を1(2-1)個飛ばしで取得し生成
print(list(range(9, 2, -2)))    # 9~3(2+1)の要素を-1(-2+1)個飛ばして取得して生成(逆順の配列)
print(list(reversed(range(3, 10, 2))))  # reversed関数を使用して逆順の配列を生成
print([i / 10 for i in range(3, 10, 2)])# range関数に指定できるのはint型のみfloatを使用する場合はリスト内包表記を使用する

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7, 8, 9]
[3, 5, 7, 9]
[9, 7, 5, 3]
[9, 7, 5, 3]
[0.3, 0.5, 0.7, 0.9]


In [2]:
# 数学の学習すべき分野
# 三角関数
# 行列
# 数列

In [16]:
# NumPyによる行列の計算
import numpy as np
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.arange(5, 9).reshape(2, 2)
print(B)
# 行列の足し算・引き算
# 
# 行・列の両方が一致していないと足し算・引き算することはできない
print('行列の足し算:\n', A + B)
print('行列の引き算:\n', A - B)

# スカラー倍
# 
# n x (a b  = (na nb
#      c d)    nc nd)
print('行列のスカラー倍:\n', 5 * A)

# 行列積
# 
# 「左の行列の列数」と「右の行列の列数」が一致していないと掛け算することはできない
# 
# (a b) x (c = ac + bd
#          d)
# 
# =================================
# A = (a b   B = (p q
#      c d),      r s)
# 
# AB = (a b (p q  = (ap+br aq+bs
#       c d) r s)    cp+dr cq+ds)
# =================================
# 
# AB != BA
print('AxBの行列積:\n', np.dot(A, B))
print('BxAの行列積:\n', np.dot(B, A))

# 転置行列
print('Aの転置行列:\n', A.T)
print('Bの転置行列:\n', B.T)

# 行列のべき乗

# 二次元行列の内積
# 行列積の全ての要素の和
print('A[0]とA[1]の内積:\n', np.dot(A[0], A[1]))
print('B[0]とB[1]の内積:\n', np.dot(B[0], B[1]))
print('AとBの内積:\n', np.vdot(A, B))

# 単位行列
# 対角成分が1、非対角成分が0である行列
# 
# A = (1 0    B = (1 0 0    C = (1 0 0 0
#      0 1)        0 1 0         0 1 0 0
#                  0 0 1)        0 0 1 0
#                                0 0 0 1)

# 逆行列
# 元の行列にかけると単位行列になるもの
# 逆行列が存在しない場合もある
# 連立一次方程式を一瞬で求められる
print('Aの逆行列:\n', np.linalg.inv(A))
print('Bの逆行列:\n', np.linalg.inv(B))

# 類似逆行列

# 行列式
# 行列の特徴を表す指標の一つ
print('Aの行列式:\n', np.linalg.det(A))
print('Bの行列式:\n', np.linalg.det(B))

# 固有値と固有ベクトル
# Ax = λxを満たすx(固有ベクトル)とλ(固有値)
# numpy.argmax()と併用して最大固有値を求める
Aの固有値, Aの固有ベクトル = np.linalg.eig(A)
print('Aの固有値:\n', Aの固有値)
print('Aの固有ベクトル:\n', Aの固有ベクトル)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
行列の足し算:
 [[ 6  8]
 [10 12]]
行列の引き算:
 [[-4 -4]
 [-4 -4]]
行列のスカラー倍:
 [[ 5 10]
 [15 20]]
AxBの行列積:
 [[19 22]
 [43 50]]
BxAの行列積:
 [[23 34]
 [31 46]]
Aの転置行列:
 [[1 3]
 [2 4]]
Bの転置行列:
 [[5 7]
 [6 8]]
A[0]とA[1]の内積:
 11
B[0]とB[1]の内積:
 83
AとBの内積:
 70
Aの逆行列:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Bの逆行列:
 [[-4.   3. ]
 [ 3.5 -2.5]]
Aの行列式:
 -2.0000000000000004
Bの行列式:
 -1.999999999999999
Aの固有値:
 [-0.37228132  5.37228132]
Aの固有ベクトル:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [62]:
# NumPyによる三角関数の計算
import numpy as np

# 円周率
print('円周率:\n', np.pi)

# 無限大
print('無限大:\n', np.inf)

# 値を丸める
# 下記の場合、小数点以下第2位まで表示する
print(np.round(np.pi, 2))

# ラジアン
# 「円(扇形)の弧の長さ÷円の半径」によって求められる値
# 弧度法と度数法の関係としては「180=π(rad)」が成り立つ

# 度からラジアンへの変換
print('数学でのラジアンの表記:\n', ['0      ', 'π/36   ', 'π/12   ', 'π/6    ', 'π/4    ', 'π/3    ', 'π/2    ', 'π/1    ', '2π     '])
print('度からラジアンへの変換:\n', np.radians([0, 5, 15, 30, 45, 60, 90, 180, 225, 360, 540]))
print('ラジアンを正弦へ変換:\n', np.sin(np.radians([0, 5, 15, 30, 45, 60, 90, 180, 225, 360, 540])))
print('ラジアンを正弦へ変換:\n', np.round(np.sin(np.radians([0, 5, 15, 30, 45, 60, 90, 180, 225, 360, 540])), 2))
print('度からラジアンへの変換:\n', np.deg2rad([0, 90, 180]))

# ラジアンから度への変換
print('ラジアンから度への変換:\n', np.degrees([0, np.pi / 2, np.pi]))
print('ラジアンから度への変換:\n', np.rad2deg([0, np.pi / 2, np.pi]))

# 正弦
print('正弦:\n', np.sin(np.radians([0, 30, 90])))

# 逆正弦
print('逆正弦:\n', np.degrees(np.arcsin([0, 0.5, 1])))

# 余弦
print('余弦:\n', np.cos(np.radians([0, 60, 90])))
print(np.round(np.cos(np.radians([0, 60, 90])), 1))

# 逆余弦
print('逆余弦:\n', np.degrees(np.arccos([0, 0.5, 1])))

# 正接
print('正接:\n', np.tan(np.radians([0, 45, 90])))

# 逆正接
print('逆正接:\n', np.degrees(np.arctan([0, 1, np.inf])))

円周率:
 3.141592653589793
無限大:
 inf
3.14
数学でのラジアンの表記:
 ['0      ', 'π/36   ', 'π/12   ', 'π/6    ', 'π/4    ', 'π/3    ', 'π/2    ', 'π/1    ', '2π     ']
度からラジアンへの変換:
 [0.         0.08726646 0.26179939 0.52359878 0.78539816 1.04719755
 1.57079633 3.14159265 3.92699082 6.28318531 9.42477796]
ラジアンを正弦へ変換:
 [ 0.00000000e+00  8.71557427e-02  2.58819045e-01  5.00000000e-01
  7.07106781e-01  8.66025404e-01  1.00000000e+00  1.22464680e-16
 -7.07106781e-01 -2.44929360e-16  3.67394040e-16]
ラジアンを正弦へ変換:
 [ 0.    0.09  0.26  0.5   0.71  0.87  1.    0.   -0.71 -0.    0.  ]
度からラジアンへの変換:
 [0.         1.57079633 3.14159265]
ラジアンから度への変換:
 [  0.  90. 180.]
ラジアンから度への変換:
 [  0.  90. 180.]
正弦:
 [0.  0.5 1. ]
逆正弦:
 [ 0. 30. 90.]
余弦:
 [1.000000e+00 5.000000e-01 6.123234e-17]
[1.  0.5 0. ]
逆余弦:
 [90. 60.  0.]
正接:
 [0.00000000e+00 1.00000000e+00 1.63312394e+16]
逆正接:
 [ 0. 45. 90.]
